### ISSUE TITLE
CI, Python Versioning, and ISIS

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/knoten#123]
This issue relates to the use of `pysis` in the library. When adding CI (#122) we saw that builds with python >=3.10 were consistently failing to solve using mamba/conda. The issue is that the `pysis` library is pinned to have an isis dependency. That dependency needs ISIS installed.

To get CI running `pysis` was swapped for `kalasiris`, which does not have a python pinning. `kalasiris` assumes that the `ISISROOT` and `ISISDATA` env variables are set. Therefore ISIS can live in a different environment.

I doubt that the swap to `kalasiris` is particularly contentious as the library has a [`pysis` style interface](https://kalasiris.readthedocs.io/en/latest/kalasiris.html#module-kalasiris.pysis) that is a straight swap in. What I think warrants more discussion is the now implicit ISIS dependency if anyone wants to use the `vis` module or run and of the comparison notebooks. Do these notebooks belong in `knoten` or are they an example consuming `knoten`? Should the notebooks include a README style entry at the top instructing users to install ISIS in a different environment AND add the necessary `os.environ` lines?

**Comment by Kelvinrr** [comment]
I dont mind potentially moving them somewhere else, it makes sense to have some kind of vis/comparison library that is different. It's been here because realistically it's been the only real use for knoten in the past. If we want to redo knoten as a lower-level language first with python wrappers, they should def be all moved out.
