### ISSUE TITLE
Requirements for running example notebooks

### ISSUE THREAD

**Issue by jessemapel** [USGS-Astrogeology/knoten#6]
What do we expect to be able to run the example notebooks? I have a couple questions that I think we need to answer before these are ready for consumption.

1. Are we generating ISDs in the notebook or are we adding them to the repo?

1. How are users getting the image files. Will the notebooks download them. Do we want to add them to the repo?

I would like to add some CI that runs the notebooks to ensure that the examples are still good.

**Comment by thareUSGS** [comment]
for 1. I like Jay's idea to have separate notebooks for ISD generate until pfeffernusse is very stable. That means will need a "data\" directory under the "examples" or "notebooks" directory.

for 2. I like how you (Jesse), were able to download the image in your example if we trust that location is stable. I think Kelvin even showed how the Kaguya data needed to be untar'd (which is good). Otherwise, the image(s) will need to be housed in "data\" also.

Since knoten imports csm for the user, I want to make sure that is very apparent. So if import "csm" is removed, please comment on what is getting imported from knoten.

**Comment by jessemapel** [comment]
We're taking this more lax, so I'm going to close this issue.
